# Generated by Django 2.2.6 on 2019-10-16 15:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kategori', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penulis', models.CharField(max_length=200)),
                ('judul', models.CharField(max_length=200)),
                ('isi', models.TextField()),
                ('tanggal_buat', models.DateTimeField(default=django.utils.timezone.now)),
                ('tanggal_post', models.DateTimeField(blank=True, null=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postingan.Kategori')),
            ],
        ),
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('komentar', models.TextField()),
                ('postingan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postingan.Post')),
            ],
        ),
    ]
